apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-detection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-detection
  template:
    metadata:
      labels:
        app: change-detection
    spec:
      containers:
      - name: change-detection-container
        image: cpd-image:local
        ports:
        - containerPort: 5012
---
apiVersion: v1
kind: Service
metadata:
  name: change-detection-service
spec:
  selector:
    app: change-detection
  ports:
    - protocol: TCP
      port: 80      # External port for access
      targetPort: 5012  # The port inside the container
